# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import flow_pb2 as proto_dot_flow__pb2


class FlowMessageClassifierStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyStreaming = channel.stream_stream(
                '/flow.FlowMessageClassifier/ClassifyStreaming',
                request_serializer=proto_dot_flow__pb2.FlowMessage.SerializeToString,
                response_deserializer=proto_dot_flow__pb2.FlowMessageClass.FromString,
                )


class FlowMessageClassifierServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClassifyStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlowMessageClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyStreaming': grpc.stream_stream_rpc_method_handler(
                    servicer.ClassifyStreaming,
                    request_deserializer=proto_dot_flow__pb2.FlowMessage.FromString,
                    response_serializer=proto_dot_flow__pb2.FlowMessageClass.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flow.FlowMessageClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FlowMessageClassifier(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClassifyStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/flow.FlowMessageClassifier/ClassifyStreaming',
            proto_dot_flow__pb2.FlowMessage.SerializeToString,
            proto_dot_flow__pb2.FlowMessageClass.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
