FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:main

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes libzmq3-dev:armhf libssl-dev:armhf libprotobuf-dev protobuf-compiler zlib1g:armhf zlib1g-dev:armhf
